-- Phase 3 episode and accounting core contract.
-- Local harness uses in-memory storage; this migration freezes the intended relational surface.

CREATE TABLE import_row (
    import_row_id text PRIMARY KEY,
    workspace_id text NOT NULL,
    trading_account_id text NOT NULL,
    import_batch_id text NOT NULL,
    source_row_number integer NOT NULL CHECK (source_row_number > 1),
    raw_row_sha256 text NOT NULL,
    status text NOT NULL CHECK (status IN ('RECONCILED', 'DUPLICATE', 'ACCOUNTING_PENDING', 'QUARANTINED')),
    safe_error_code text NULL,
    normalized_fill_id text NULL,
    duplicate_of_fill_id text NULL,
    staged_fill_id text NULL,
    recorded_at text NOT NULL,
    UNIQUE (workspace_id, import_batch_id, source_row_number),
    FOREIGN KEY (import_batch_id) REFERENCES import_batch (import_batch_id),
    FOREIGN KEY (workspace_id, trading_account_id) REFERENCES trading_account (workspace_id, trading_account_id)
);

CREATE TABLE normalized_fill (
    fill_id text PRIMARY KEY,
    workspace_id text NOT NULL,
    trading_account_id text NOT NULL,
    import_batch_id text NOT NULL,
    import_row_id text NOT NULL,
    source_row_number integer NOT NULL,
    import_contract_version text NOT NULL CHECK (import_contract_version = 'binance_spot_trade_history_csv_v1'),
    fill_schema_version text NOT NULL CHECK (fill_schema_version = 'normalized_fill_v1'),
    instrument_catalog_version text NOT NULL,
    venue text NOT NULL CHECK (venue = 'BINANCE'),
    product_type text NOT NULL CHECK (product_type = 'SPOT'),
    instrument_id text NOT NULL,
    venue_symbol text NOT NULL,
    base_asset text NOT NULL,
    quote_asset text NOT NULL CHECK (quote_asset = 'USDT'),
    side text NOT NULL CHECK (side IN ('BUY', 'SELL')),
    executed_at text NOT NULL,
    source_timestamp_precision text NOT NULL CHECK (source_timestamp_precision IN ('SECOND', 'MILLISECOND')),
    source_time_start text NOT NULL,
    source_time_end_exclusive text NOT NULL,
    price_quote_per_base text NOT NULL,
    executed_qty_base text NOT NULL,
    gross_amount_quote text NOT NULL,
    fee_qty text NOT NULL,
    fee_asset text NOT NULL,
    canonical_signature_sha256 text NOT NULL,
    occurrence_index integer NOT NULL CHECK (occurrence_index > 0),
    dedup_key text NOT NULL,
    created_at text NOT NULL,
    UNIQUE (workspace_id, import_row_id),
    UNIQUE (trading_account_id, dedup_key),
    FOREIGN KEY (import_batch_id) REFERENCES import_batch (import_batch_id),
    FOREIGN KEY (import_row_id) REFERENCES import_row (import_row_id),
    FOREIGN KEY (workspace_id, trading_account_id) REFERENCES trading_account (workspace_id, trading_account_id)
);

CREATE TABLE fee_conversion (
    fee_conversion_id text PRIMARY KEY,
    workspace_id text NOT NULL,
    fill_id text NOT NULL,
    conversion_version integer NOT NULL CHECK (conversion_version > 0),
    fee_asset text NOT NULL,
    quote_asset text NOT NULL CHECK (quote_asset = 'USDT'),
    fee_qty text NOT NULL,
    status text NOT NULL CHECK (status IN ('EXACT', 'DERIVED', 'UNAVAILABLE')),
    method text NULL CHECK (method IS NULL OR method IN ('EXACT', 'NATIVE_QUOTE', 'FILL_RATE', 'DIRECT_1M_CLOSE', 'INVERSE_1M_CLOSE')),
    rate_quote_per_fee_asset text NULL,
    fee_value_quote text NULL,
    as_of_at text NULL,
    algorithm_version text NOT NULL CHECK (algorithm_version = 'fee_conversion_v1'),
    created_at text NOT NULL,
    superseded_at text NULL,
    UNIQUE (workspace_id, fill_id, conversion_version),
    FOREIGN KEY (fill_id) REFERENCES normalized_fill (fill_id)
);

CREATE TABLE trade_episode (
    episode_id text PRIMARY KEY,
    workspace_id text NOT NULL,
    trading_account_id text NOT NULL,
    instrument_id text NOT NULL,
    opening_fill_id text NOT NULL,
    opening_fill_dedup_key text NOT NULL,
    created_at text NOT NULL,
    UNIQUE (workspace_id, episode_id),
    UNIQUE (trading_account_id, instrument_id, opening_fill_dedup_key),
    FOREIGN KEY (opening_fill_id) REFERENCES normalized_fill (fill_id),
    FOREIGN KEY (workspace_id, trading_account_id) REFERENCES trading_account (workspace_id, trading_account_id)
);

CREATE TABLE trade_episode_projection (
    episode_id text NOT NULL,
    projection_version integer NOT NULL CHECK (projection_version > 0),
    projection_algorithm_version text NOT NULL CHECK (projection_algorithm_version = 'episode_projection_v1'),
    ledger_algorithm_version text NOT NULL CHECK (ledger_algorithm_version = 'wac_episode_v1'),
    workspace_id text NOT NULL,
    trading_account_id text NOT NULL,
    instrument_id text NOT NULL,
    quote_asset text NOT NULL CHECK (quote_asset = 'USDT'),
    state text NOT NULL CHECK (state IN ('OPEN', 'CLOSED')),
    first_fill_id text NOT NULL,
    first_fill_at text NOT NULL,
    first_fill_time_end_exclusive text NOT NULL,
    first_fill_timestamp_precision text NOT NULL,
    closed_fill_id text NULL,
    closed_at text NULL,
    closed_time_end_exclusive text NULL,
    closed_timestamp_precision text NULL,
    associated_plan_id text NULL,
    associated_plan_revision_id text NULL,
    frozen_plan_revision_id text NULL,
    plan_proof_status text NOT NULL CHECK (plan_proof_status IN ('VERIFIED', 'AMBIGUOUS', 'LATE', 'UNMATCHED')),
    plan_proof_reason_code text NOT NULL,
    plan_proof_rule_version text NOT NULL CHECK (plan_proof_rule_version = 'plan_proof_v1'),
    plan_candidate_ids_json text NOT NULL,
    plan_proof_basis_json text NOT NULL,
    plan_proof_resolved_at text NOT NULL,
    late_association_id text NULL,
    plan_match_resolution_id text NULL,
    position_qty_base text NOT NULL,
    open_cost_basis_quote text NOT NULL,
    average_cost_quote_per_base text NULL,
    gross_realized_pnl_quote text NOT NULL,
    known_fee_quote text NOT NULL,
    net_realized_pnl_quote text NULL,
    planned_initial_risk_quote text NULL,
    r_multiple text NULL,
    accounting_quality text NOT NULL CHECK (accounting_quality IN ('COMPLETE', 'FEE_CONVERSION_MISSING', 'LEDGER_INVARIANT_FAILED')),
    created_at text NOT NULL,
    superseded_at text NULL,
    PRIMARY KEY (episode_id, projection_version),
    FOREIGN KEY (episode_id) REFERENCES trade_episode (episode_id),
    FOREIGN KEY (first_fill_id) REFERENCES normalized_fill (fill_id)
);

CREATE TABLE episode_fill_allocation (
    episode_id text NOT NULL,
    workspace_id text NOT NULL,
    projection_version integer NOT NULL,
    fill_id text NOT NULL,
    event_sequence integer NOT NULL CHECK (event_sequence > 0),
    position_qty_before text NOT NULL,
    position_qty_delta text NOT NULL,
    position_qty_after text NOT NULL,
    cost_basis_before text NOT NULL,
    cost_basis_delta text NOT NULL,
    cost_basis_after text NOT NULL,
    gross_realized_delta_quote text NOT NULL,
    fee_expense_delta_quote text NULL,
    PRIMARY KEY (episode_id, projection_version, event_sequence),
    UNIQUE (episode_id, projection_version, fill_id),
    FOREIGN KEY (episode_id, projection_version) REFERENCES trade_episode_projection (episode_id, projection_version),
    FOREIGN KEY (fill_id) REFERENCES normalized_fill (fill_id)
);

CREATE TABLE accounting_ledger_entry (
    ledger_entry_id text PRIMARY KEY,
    workspace_id text NOT NULL,
    episode_id text NOT NULL,
    projection_version integer NOT NULL,
    fill_id text NOT NULL,
    entry_sequence integer NOT NULL CHECK (entry_sequence > 0),
    entry_type text NOT NULL CHECK (entry_type IN ('TRADE', 'FEE')),
    occurred_at text NOT NULL,
    asset text NOT NULL,
    asset_qty_delta text NOT NULL,
    quote_asset text NOT NULL CHECK (quote_asset = 'USDT'),
    quote_value_delta text NULL,
    position_qty_delta_base text NOT NULL,
    cost_basis_delta_quote text NOT NULL,
    gross_realized_delta_quote text NOT NULL,
    fee_expense_delta_quote text NULL,
    fee_conversion_id text NULL,
    algorithm_version text NOT NULL CHECK (algorithm_version = 'wac_episode_v1'),
    created_at text NOT NULL,
    UNIQUE (workspace_id, episode_id, projection_version, entry_sequence),
    UNIQUE (workspace_id, episode_id, projection_version, fill_id, entry_type),
    FOREIGN KEY (episode_id, projection_version) REFERENCES trade_episode_projection (episode_id, projection_version),
    FOREIGN KEY (fill_id) REFERENCES normalized_fill (fill_id),
    FOREIGN KEY (fee_conversion_id) REFERENCES fee_conversion (fee_conversion_id)
);
